# Site settings
title: Yuta Nakamura 
email: yutanak6@gmail.com
# url: https://github.com/jeromelachaud/freelancer-theme
description: "I'd like to solve problems of the world today."
keywords: "Computer Systems, Graph Theory"
skills: "Ph.D. student at DePaul University"
meta_author: Nakamura Yuta

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: yuta 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 80B3FF #18bc9c
  primary-rgb: "128,179,255" #"24,288,156"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Yuta Nakamura 
  location: Address
  social: Social 
    # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/nakasan617
  - title: linkedin
    url: https://www.linkedin.com/in/yuta-nakamura-93b9b778/

# Postal address (add as many lines as necessary)
address:
  - line: 222 W. 26th st.
  - line: Chicago, IL 60616 

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
